language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sonupatel10906997/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sonupatel10906997/react-test npm test

  after_success:
    - docker build -t sonupatel10906997/multi-client ./client
    - docker build -t sonupatel10906997/multi-nginx ./nginx
    - docker build -t sonupatel10906997/multi-server ./nginx
    - docker build -t sonupatel10906997/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to docker hub
    - docker push sonupatel10906997/multi-client
    - docker push sonupatel10906997/multi-nginx
    - docker push sonupatel10906997/multi-server
    - docker push sonupatel10906997/multi-worker